from sqlalchemy import Column, String, Integer, Float, DateTime, Boolean, Date, func
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class BaseModel(Base):
    __abstract__ = True
    id = Column(Integer, primary_key=True, autoincrement=True)

class NFLSchedules(BaseModel):
    __tablename__ = 'nfl_schedules'
    game_id = Column(String, nullable=False)
    season = Column(Integer, nullable=False)
    week = Column(Integer, nullable=False)
    game_type = Column(String)
    gameday = Column(DateTime)
    weekday = Column(String)
    gametime = Column(String)
    away_team = Column(String)
    away_score = Column(Float)
    home_team = Column(String)
    home_score = Column(Float)
    location = Column(String)
    result = Column(Float)
    total = Column(Float)
    overtime = Column(Boolean)
    old_game_id = Column(Integer)
    gsis = Column(Integer)
    nfl_detail_id = Column(String)
    pfr = Column(String)
    pff = Column(String)
    espn = Column(Integer)
    ftn = Column(Float)
    away_rest = Column(Integer)
    home_rest = Column(Integer)
    away_moneyline = Column(Float)
    home_moneyline = Column(Float)
    spread_line = Column(Float)
    away_spread_odds = Column(Float)
    home_spread_odds = Column(Float)
    total_line = Column(Float)
    over_odds = Column(Float)
    under_odds = Column(Float)
    div_game = Column(Boolean)
    roof = Column(String)
    surface = Column(String)
    temp = Column(Float)
    wind = Column(Float)
    away_qb_id = Column(String)
    home_qb_id = Column(String)
    away_qb_name = Column(String)
    home_qb_name = Column(String)
    away_coach = Column(String)
    home_coach = Column(String)
    referee = Column(String)
    stadium_id = Column(String)
    stadium = Column(String)

class NFLWeeklyRosters(BaseModel):
    __tablename__ = 'nfl_weekly_rosters'
    season = Column(Integer, nullable=False)
    week = Column(Integer, nullable=False)
    team = Column(String, nullable=False)
    position = Column(String)
    depth_chart_position = Column(String)
    jersey_number = Column(Float)
    status = Column(String)
    player_name = Column(String)
    first_name = Column(String)
    last_name = Column(String)
    birth_date = Column(DateTime)
    height = Column(Float)
    weight = Column(Float)
    college = Column(String)
    player_id = Column(String)
    espn_id = Column(String)
    sportradar_id = Column(String)
    yahoo_id = Column(String)
    rotowire_id = Column(String)
    pff_id = Column(String)
    pfr_id = Column(String)
    fantasy_data_id = Column(String)
    sleeper_id = Column(String)
    esb_id = Column(String)
    gsis_it_id = Column(String)
    smart_id = Column(String)
    years_exp = Column(Integer)
    headshot_url = Column(String)
    ngs_position = Column(String)
    status_description_abbr = Column(String)
    football_name = Column(String)
    entry_year = Column(Integer)
    rookie_year = Column(Float)
    draft_club = Column(String)
    draft_number = Column(Float)
    game_type = Column(String)
    age = Column(Float)

class NFLWeeklyData(BaseModel):
    __tablename__ = 'nfl_weekly_data'
    player_id = Column(String, nullable=False)
    player_name = Column(String, nullable=False)
    player_display_name = Column(String)
    position = Column(String)
    position_group = Column(String)
    headshot_url = Column(String)
    recent_team = Column(String)
    season = Column(Integer, nullable=False)
    week = Column(Integer, nullable=False)
    season_type = Column(String)
    opponent_team = Column(String)
    completions = Column(Integer)
    attempts = Column(Integer)
    passing_yards = Column(Float)
    passing_tds = Column(Integer)
    interceptions = Column(Float)
    sacks = Column(Float)
    sack_yards = Column(Float)
    sack_fumbles = Column(Integer)
    sack_fumbles_lost = Column(Integer)
    passing_air_yards = Column(Float)
    passing_yards_after_catch = Column(Float)
    passing_first_downs = Column(Float)
    passing_epa = Column(Float)
    passing_2pt_conversions = Column(Integer)
    pacr = Column(Float)
    dakota = Column(Float)
    carries = Column(Integer)
    rushing_yards = Column(Float)
    rushing_tds = Column(Integer)
    rushing_fumbles = Column(Float)
    rushing_fumbles_lost = Column(Float)
    rushing_first_downs = Column(Float)
    rushing_epa = Column(Float)
    rushing_2pt_conversions = Column(Integer)
    receptions = Column(Integer)
    targets = Column(Integer)
    receiving_yards = Column(Float)
    receiving_tds = Column(Integer)
    receiving_fumbles = Column(Float)
    receiving_fumbles_lost = Column(Float)
    receiving_air_yards = Column(Float)
    receiving_yards_after_catch = Column(Float)
    receiving_first_downs = Column(Float)
    receiving_epa = Column(Float)
    receiving_2pt_conversions = Column(Integer)
    racr = Column(Float)
    target_share = Column(Float)
    air_yards_share = Column(Float)
    wopr = Column(Float)
    special_teams_tds = Column(Float)
    fantasy_points = Column(Float)
    fantasy_points_ppr = Column(Float)

class NFLInjuryData(BaseModel):
    __tablename__ = 'nfl_injury_data'

    season = Column(Integer, nullable=False)
    game_type = Column(String)
    team = Column(String)
    week = Column(Integer, nullable=False)
    gsis_id = Column(String)
    position = Column(String)
    full_name = Column(String)
    first_name = Column(String)
    last_name = Column(String)
    report_primary_injury = Column(String)
    report_secondary_injury = Column(String)
    report_status = Column(String)
    practice_primary_injury = Column(String)
    practice_secondary_injury = Column(String)
    practice_status = Column(String)
    date_modified = Column(DateTime)

class NFLWeeklyDataWithScores(BaseModel):
    __tablename__ = 'nfl_weekly_data_with_scores'

    # Include all columns from NFLWeeklyData
    player_id = Column(String, nullable=False)
    player_name = Column(String, nullable=False)
    player_display_name = Column(String)
    position = Column(String)
    position_group = Column(String)
    headshot_url = Column(String)
    recent_team = Column(String)
    season = Column(Integer, nullable=False)
    week = Column(Integer, nullable=False)
    season_type = Column(String)
    opponent_team = Column(String)
    completions = Column(Integer)
    attempts = Column(Integer)
    passing_yards = Column(Float)
    passing_tds = Column(Integer)
    interceptions = Column(Float)
    sacks = Column(Float)
    sack_yards = Column(Float)
    sack_fumbles = Column(Integer)
    sack_fumbles_lost = Column(Integer)
    passing_air_yards = Column(Float)
    passing_yards_after_catch = Column(Float)
    passing_first_downs = Column(Float)
    passing_epa = Column(Float)
    passing_2pt_conversions = Column(Integer)
    pacr = Column(Float)
    dakota = Column(Float)
    carries = Column(Integer)
    rushing_yards = Column(Float)
    rushing_tds = Column(Integer)
    rushing_fumbles = Column(Float)
    rushing_fumbles_lost = Column(Float)
    rushing_first_downs = Column(Float)
    rushing_epa = Column(Float)
    rushing_2pt_conversions = Column(Integer)
    receptions = Column(Integer)
    targets = Column(Integer)
    receiving_yards = Column(Float)
    receiving_tds = Column(Integer)
    receiving_fumbles = Column(Float)
    receiving_fumbles_lost = Column(Float)
    receiving_air_yards = Column(Float)
    receiving_yards_after_catch = Column(Float)
    receiving_first_downs = Column(Float)
    receiving_epa = Column(Float)
    receiving_2pt_conversions = Column(Integer)
    racr = Column(Float)
    target_share = Column(Float)
    air_yards_share = Column(Float)
    wopr = Column(Float)
    special_teams_tds = Column(Float)
    fantasy_points = Column(Float)
    fantasy_points_ppr = Column(Float)

    # Additional columns for DK scores
    dk_pass_yds_points = Column(Float)
    dk_pass_td_points = Column(Float)
    dk_int_points = Column(Float)
    dk_rush_yds_points = Column(Float)
    dk_rush_td_points = Column(Float)
    dk_rec_points = Column(Float)
    dk_rec_yds_points = Column(Float)
    dk_rec_td_points = Column(Float)
    dk_fum_lost_points = Column(Float)
    dk_pass_300_bonus = Column(Float)
    dk_rush_100_bonus = Column(Float)
    dk_rec_100_bonus = Column(Float)
    dk_rush_2pt_points = Column(Float)
    dk_rec_2pt_points = Column(Float)
    dk_pass_2pt_points = Column(Float)
    dk_total_points = Column(Float)
    dk_salary = Column(Integer)
    salary_points_ratio = Column(Float)

class DKSalaries(BaseModel):
    __tablename__ = 'dk_salaries'
    position = Column(String, nullable=False)
    name = Column(String, nullable=False)
    name_and_id = Column(String, nullable=False)
    player_id = Column(Integer, nullable=False)
    salary = Column(Integer, nullable=False)
    game_info = Column(String, nullable=False)
    roster_position = Column(String, nullable=False)
    week = Column(Integer, nullable=False)
    season = Column(Integer, nullable=False)
    player_team = Column(String, nullable=False)
    average_points_per_game = Column(Float, nullable=False)
    slate = Column(String, nullable=False)

class WeeklyInjuries(BaseModel):
    __tablename__ = 'weekly_injuries'
    player_id = Column(String, nullable=False)
    position = Column(String, nullable=False)
    first_name = Column(String, nullable=False)
    nickname = Column(String, nullable=False)
    last_name = Column(String, nullable=False)
    fppg = Column(Float, nullable=False)
    played = Column(String, nullable=False)
    salary = Column(Integer, nullable=False)
    game_info = Column(String, nullable=False)
    team = Column(String, nullable=False)
    opponent = Column(String, nullable=False)
    injury_indicator = Column(String, nullable=False)
    injury_details = Column(String, nullable=False)
    tier = Column(String, nullable=False)
    roster_position = Column(String, nullable=False)
    week = Column(Integer, nullable=False)
    season = Column(Integer, nullable=False)
    slate = Column(String)

class StartingQBs(BaseModel):
    __tablename__ = 'starting_qbs'
    player_id = Column(String, nullable=False)
    player_name = Column(String, nullable=False)
    team = Column(String, nullable=False)
    opponent = Column(String)
    season = Column(Integer, nullable=False)
    week = Column(Integer, nullable=False)
    slate = Column(String)
    status = Column(String)  # active, questionable, out, unknown
    source = Column(String)  # derived, manual

class PlayerSeasonAverages(BaseModel):
    __tablename__ = 'player_season_averages'

    player_id = Column(String, nullable=False)
    player_display_name = Column(String)
    position = Column(String)
    position_group = Column(String)
    headshot_url = Column(String)
    recent_team = Column(String)
    season = Column(Integer, nullable=False)
    season_type = Column(String)
    completions = Column(Float)
    attempts = Column(Float)
    passing_yards = Column(Float)
    passing_tds = Column(Float)
    interceptions = Column(Float)
    passing_air_yards = Column(Float)
    passing_yards_after_catch = Column(Float)
    passing_first_downs = Column(Float)
    passing_epa = Column(Float)
    passing_2pt_conversions = Column(Float)
    pacr = Column(Float)
    dakota = Column(Float)
    carries = Column(Float)
    rushing_yards = Column(Float)
    rushing_tds = Column(Float)
    rushing_fumbles = Column(Float)
    rushing_fumbles_lost = Column(Float)
    rushing_first_downs = Column(Float)
    rushing_epa = Column(Float)
    rushing_2pt_conversions = Column(Float)
    receptions = Column(Float)
    targets = Column(Float)
    receiving_yards = Column(Float)
    receiving_tds = Column(Float)
    receiving_fumbles = Column(Float)
    receiving_fumbles_lost = Column(Float)
    receiving_air_yards = Column(Float)
    receiving_yards_after_catch = Column(Float)
    receiving_first_downs = Column(Float)
    receiving_epa = Column(Float)
    receiving_2pt_conversions = Column(Float)
    racr = Column(Float)
    target_share = Column(Float)
    air_yards_share = Column(Float)
    wopr = Column(Float)
    special_teams_tds = Column(Float)
    fantasy_points = Column(Float)
    fantasy_points_ppr = Column(Float)
    dk_pass_yds_points = Column(Float)
    dk_pass_td_points = Column(Float)
    dk_int_points = Column(Float)
    dk_rush_yds_points = Column(Float)
    dk_rush_td_points = Column(Float)
    dk_rec_points = Column(Float)
    dk_rec_yds_points = Column(Float)
    dk_rec_td_points = Column(Float)
    dk_fum_lost_points = Column(Float)
    dk_pass_300_bonus = Column(Float)
    dk_rush_100_bonus = Column(Float)
    dk_rec_100_bonus = Column(Float)
    dk_rush_2pt_points = Column(Float)
    dk_rec_2pt_points = Column(Float)
    dk_pass_2pt_points = Column(Float)
    dk_total_points = Column(Float)


class TeamSeasonPositionDefense(BaseModel):
    __tablename__ = 'team_season_position_defense'

    recent_team = Column(String, primary_key=True)
    season = Column(Integer, primary_key=True)
    position = Column(String)
    opponent_team = Column(String)
    season_type = Column(String)
    completions = Column(Integer)
    attempts = Column(Integer)
    passing_yards = Column(Float)
    passing_tds = Column(Integer)
    interceptions = Column(Float)
    sacks = Column(Float)
    sack_yards = Column(Float)
    sack_fumbles = Column(Integer)
    sack_fumbles_lost = Column(Integer)
    passing_air_yards = Column(Float)
    passing_yards_after_catch = Column(Float)
    passing_first_downs = Column(Float)
    passing_epa = Column(Float)
    passing_2pt_conversions = Column(Integer)
    carries = Column(Integer)
    rushing_yards = Column(Float)
    rushing_tds = Column(Integer)
    rushing_fumbles = Column(Float)
    rushing_fumbles_lost = Column(Float)
    rushing_first_downs = Column(Float)
    rushing_epa = Column(Float)
    rushing_2pt_conversions = Column(Integer)
    receptions = Column(Integer)
    targets = Column(Integer)
    receiving_yards = Column(Float)
    receiving_tds = Column(Integer)
    receiving_fumbles = Column(Float)
    receiving_fumbles_lost = Column(Float)
    receiving_air_yards = Column(Float)
    receiving_yards_after_catch = Column(Float)
    receiving_first_downs = Column(Float)
    receiving_epa = Column(Float)
    receiving_2pt_conversions = Column(Integer)
    special_teams_tds = Column(Float)
    fantasy_points = Column(Float)
    fantasy_points_ppr = Column(Float)
    dk_pass_yds_points = Column(Float)
    dk_pass_td_points = Column(Float)
    dk_int_points = Column(Float)
    dk_rush_yds_points = Column(Float)
    dk_rush_td_points = Column(Float)
    dk_rec_points = Column(Float)
    dk_rec_yds_points = Column(Float)
    dk_rec_td_points = Column(Float)
    dk_fum_lost_points = Column(Float)
    dk_pass_300_bonus = Column(Float)
    dk_rush_100_bonus = Column(Float)
    dk_rec_100_bonus = Column(Float)
    dk_rush_2pt_points = Column(Float)
    dk_rec_2pt_points = Column(Float)
    dk_pass_2pt_points = Column(Float)
    dk_total_points = Column(Float)

class SeasonalData(Base):
    __tablename__ = 'seasonal_data'  # Name of the table in the database

    id = Column(Integer, primary_key=True, autoincrement=True)
    player_id = Column(String, nullable=False)  # Ensure this matches the data returned
    season = Column(Integer, nullable=False)
    season_type = Column(String)  # e.g., 'REG', 'POST'
    completions = Column(Integer)
    attempts = Column(Integer)
    passing_yards = Column(Float)
    passing_tds = Column(Integer)
    interceptions = Column(Float)
    sacks = Column(Float)
    sack_yards = Column(Float)
    sack_fumbles = Column(Integer)
    sack_fumbles_lost = Column(Integer)
    passing_air_yards = Column(Float)
    passing_yards_after_catch = Column(Float)
    passing_first_downs = Column(Float)
    passing_epa = Column(Float)
    passing_2pt_conversions = Column(Integer)
    pacr = Column(Float)
    dakota = Column(Float)
    carries = Column(Integer)
    rushing_yards = Column(Float)
    rushing_tds = Column(Integer)
    rushing_fumbles = Column(Float)
    rushing_fumbles_lost = Column(Float)
    rushing_first_downs = Column(Float)
    rushing_epa = Column(Float)
    rushing_2pt_conversions = Column(Integer)
    receptions = Column(Integer)
    targets = Column(Integer)
    receiving_yards = Column(Float)
    receiving_tds = Column(Integer)
    receiving_fumbles = Column(Float)
    receiving_fumbles_lost = Column(Float)
    receiving_air_yards = Column(Float)
    receiving_yards_after_catch = Column(Float)
    receiving_first_downs = Column(Float)
    receiving_epa = Column(Float)
    receiving_2pt_conversions = Column(Integer)
    racr = Column(Float)
    target_share = Column(Float)
    air_yards_share = Column(Float)
    wopr_x = Column(Float)
    special_teams_tds = Column(Integer)
    fantasy_points = Column(Float)
    fantasy_points_ppr = Column(Float)
    games = Column(Integer)
    tgt_sh = Column(Float)  # Target Share
    ay_sh = Column(Float)   # Air Yards Share
    yac_sh = Column(Float)  # Yards After Catch Share
    wopr_y = Column(Float)   # Weighted Opportunity Rating (updated)
    ry_sh = Column(Float)    # Receiving Yards Share
    rtd_sh = Column(Float)   # Receiving TDs Share
    rfd_sh = Column(Float)   # Receiving 1st Downs Share
    rtdfd_sh = Column(Float) # Receiving TDs + 1st Downs Share
    dom = Column(Float)      # Dominator Rating
    w8dom = Column(Float)    # Weighted Dominator Rating
    yptmpa = Column(Float)   # Yards Per Team Pass Attempt
    ppr_sh = Column(Float)   # PPR Fantasy Points Share

    def __repr__(self):
        return f"<SeasonalData(player_id={self.player_id}, season={self.season}, season_type={self.season_type}, completions={self.completions})>"
